# Generated by Django 5.1.1 on 2024-12-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optivisionapp', '0002_frame_cart_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_uid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optivisionapp.modeldata'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optivisionapp.modeldata'),
        ),
    ]
