# Generated by Django 5.1.1 on 2024-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optivisionapp', '0003_modeldata_alter_cart_frame_alter_rating_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
    ]
