# Generated by Django 5.1.1 on 2024-12-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optivisionapp', '0004_modeldata_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='modeldata',
            name='description',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
