# Generated by Django 5.1.1 on 2025-01-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optivisionapp', '0005_delete_frame_delete_review_modeldata_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='description',
            field=models.CharField(default='default_description', max_length=255),
        ),
    ]
