# Generated by Django 5.1.1 on 2025-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optivisionapp', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
